# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('fio_plus_one', models.CharField(blank=True, max_length=255, verbose_name='ФИО + 1')),
                ('will_attend', models.BooleanField(default=True, verbose_name='Сможете ли вы присутствовать')),
                ('alcohol_preferences', models.JSONField(blank=True, default=list, help_text='Список выбранных вариантов: vodka, kedrovka, wine, champagne, custom, no_alcohol', verbose_name='Предпочтения по алкогольным напиткам')),
                ('custom_alcohol', models.CharField(blank=True, max_length=255, verbose_name='Свой вариант алкоголя')),
                ('non_alcohol_preferences', models.JSONField(blank=True, default=list, help_text='Список выбранных: juice, soda, water, compote, custom', verbose_name='Предпочтения по безалкогольным напиткам')),
                ('custom_non_alcohol', models.CharField(blank=True, max_length=255, verbose_name='Безалкогольный свой вариант')),
                ('overnight_stay', models.BooleanField(default=False, verbose_name='Планируете ли остаться с ночевой')),
                ('transfer_to_venue', models.BooleanField(default=False, verbose_name='Мне нужен трансфер до базы отдыха')),
                ('transfer_home', models.BooleanField(default=False, verbose_name='Мне нужен трансфер до дома')),
                ('transfer_address', models.CharField(blank=True, max_length=500, verbose_name='Адрес трансфера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ответ гостя',
                'verbose_name_plural': 'Ответы гостей',
                'ordering': ['-created_at'],
            },
        ),
    ]
